import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient, type SupabaseClient, type User } from '@supabase/supabase-js';
import Papa from 'papaparse';
import { ArrowUpRight, Bell, ChevronDown, CircleDollarSign, FileText, LayoutDashboard, Menu, Plus, Search, Settings, Sparkles, Upload, Users, X, Zap } from 'lucide-react';
import './styles.css';

type Invoice = { id:string; invoice_number:string; customer_name:string; amount:number; amount_paid:number; due_date:string; status:'paid'|'open'|'overdue'; };
type Customer = { id:string; name:string; email?:string|null; };

const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const supabase: SupabaseClient | null = envUrl && envKey ? createClient(envUrl, envKey) : null;

const demoInvoices: Invoice[] = [
  {id:'1',invoice_number:'INV-1048',customer_name:'Apex Studio',amount:86000,amount_paid:0,due_date:'2026-08-22',status:'overdue'},
  {id:'2',invoice_number:'INV-1047',customer_name:'Northstar Foods',amount:54000,amount_paid:10000,due_date:'2026-08-28',status:'overdue'},
  {id:'3',invoice_number:'INV-1046',customer_name:'Kite Logistics',amount:128000,amount_paid:0,due_date:'2026-09-04',status:'open'},
  {id:'4',invoice_number:'INV-1045',customer_name:'Mango Retail',amount:42000,amount_paid:42000,due_date:'2026-08-14',status:'paid'},
  {id:'5',invoice_number:'INV-1044',customer_name:'Orbit Media',amount:73000,amount_paid:0,due_date:'2026-09-07',status:'open'}
];

function money(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v)}
function daysLate(date:string){return Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000))}
function daysUntil(date:string){return Math.ceil((new Date(date).getTime()-Date.now())/86400000)}
function App(){
  const [user,setUser]=useState<User|null>(null);
  const [businessId,setBusinessId]=useState<string|null>(null);
  const [invoices,setInvoices]=useState<Invoice[]>(demoInvoices);
  const [customers,setCustomers]=useState<Customer[]>([]);
  const [page,setPage]=useState('Overview');
  const [query,setQuery]=useState('');
  const [showAdd,setShowAdd]=useState(false);
  const [showImport,setShowImport]=useState(false);
  const [toast,setToast]=useState('');
  const [menuOpen,setMenuOpen]=useState(false);
  const [navOpen,setNavOpen]=useState(false);
  const [loading,setLoading]=useState(false);
  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const [authMode,setAuthMode]=useState<'login'|'signup'>('login');

  useEffect(()=>{if(!supabase) return; supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return ()=>subscription.unsubscribe()},[]);
  useEffect(()=>{if(!supabase||!user) return; (async()=>{const {data:b}=await supabase.from('collectai_businesses').select('id').eq('owner_user_id',user.id).limit(1).maybeSingle(); if(b?.id){setBusinessId(b.id); const [inv, cus]=await Promise.all([supabase.from('collectai_invoices').select('id,invoice_number,amount,amount_paid,due_date,status,collectai_customers(name)').eq('business_id',b.id).order('due_date',{ascending:true}),supabase.from('collectai_customers').select('id,name,email').eq('business_id',b.id)]); if(inv.data)setInvoices(inv.data.map((x:any)=>({...x,customer_name:x.collectai_customers?.name??'Unknown'}))); if(cus.data)setCustomers(cus.data)} })()},[user]);

  useEffect(()=>{setNavOpen(false)},[page]);
  const filtered=useMemo(()=>invoices.filter(x=>[x.invoice_number,x.customer_name,x.status].join(' ').toLowerCase().includes(query.toLowerCase())),[invoices,query]);
  const outstanding=invoices.reduce((s,x)=>s+(x.amount-x.amount_paid),0);
  const overdue=invoices.filter(x=>x.status==='overdue').reduce((s,x)=>s+(x.amount-x.amount_paid),0);
  const recovered=invoices.reduce((s,x)=>s+x.amount_paid,0);
  const dueSoon=invoices.filter(x=>x.status==='open'&&daysUntil(x.due_date)>=0&&daysUntil(x.due_date)<=7).reduce((s,x)=>s+(x.amount-x.amount_paid),0);

  async function auth(){setLoading(true); if(!supabase){setToast('Demo mode: connect Supabase in .env to enable account login.'); setLoading(false); return} const fn=authMode==='login'?supabase.auth.signInWithPassword({email,password}):supabase.auth.signUp({email,password}); const {error}=await fn; setToast(error?.message??(authMode==='login'?'Welcome back.':'Account created.')); setLoading(false)}
  async function signOut(){await supabase?.auth.signOut(); setUser(null);setBusinessId(null)}
  async function createInvoice(payload:Omit<Invoice,'id'|'status'|'customer_name'> & {customer_name:string}){
    const status=payload.amount_paid>=payload.amount?'paid':new Date(payload.due_date)<new Date()?'overdue':'open';
    const local={...payload,id:crypto.randomUUID(),status} as Invoice; setInvoices(v=>[local,...v]); setShowAdd(false); setToast('Invoice added');
    if(supabase&&businessId){let customer=customers.find(c=>c.name.toLowerCase()===payload.customer_name.toLowerCase()); if(!customer){const r=await supabase.from('collectai_customers').insert({business_id:businessId,name:payload.customer_name}).select('id,name,email').single(); customer=r.data??undefined} await supabase.from('collectai_invoices').insert({business_id:businessId,customer_id:customer?.id,invoice_number:payload.invoice_number,amount:payload.amount,amount_paid:payload.amount_paid,due_date:payload.due_date,status,source:'manual'});}
  }
  async function importCsv(file:File){Papa.parse<Record<string,string>>(file,{header:true,skipEmptyLines:true,complete:async(r)=>{let n=0; for(const row of r.data){const amount=Number(String(row.amount||row.total||'0').replace(/[^0-9.-]/g,'')); if(!row.invoice_number||!amount)continue; await createInvoice({invoice_number:row.invoice_number,customer_name:row.customer_name||row.customer||'Unknown',amount,amount_paid:Number(row.amount_paid||row.paid||0),due_date:row.due_date||row.due||new Date().toISOString().slice(0,10)}); n++} setShowImport(false);setToast(`${n} invoice${n===1?'':'s'} imported`);}})}

  if(!user && supabase) return <Auth email={email} setEmail={setEmail} password={password} setPassword={setPassword} authMode={authMode} setAuthMode={setAuthMode} auth={auth} loading={loading}/>;

  return <div className="app">{navOpen&&<div className="scrim" onClick={()=>setNavOpen(false)}/>}<aside className={`sidebar${navOpen?' open':''}`}><div className="brand"><div className="brandMark"><Zap size={18} fill="currentColor"/></div><span>CollectAI</span></div><div className="navGroup"><div className="navLabel">WORKSPACE</div><Nav icon={<LayoutDashboard size={18}/>} label="Overview" active={page==='Overview'} onClick={()=>setPage('Overview')}/><Nav icon={<FileText size={18}/>} label="Invoices" active={page==='Invoices'} onClick={()=>setPage('Invoices')} badge={invoices.filter(i=>i.status==='overdue').length}/><Nav icon={<Bell size={18}/>} label="Reminders" active={page==='Reminders'} onClick={()=>setPage('Reminders')}/><Nav icon={<Users size={18}/>} label="Customers" active={page==='Customers'} onClick={()=>setPage('Customers')}/></div><div className="sideBottom"><Nav icon={<Settings size={18}/>} label="Settings" active={page==='Settings'} onClick={()=>setPage('Settings')}/><div className="trial"><div><Sparkles size={16}/><span>Automation active</span></div><p>Overdue invoices are checked daily.</p></div></div></aside>
    <main className="main"><header className="topbar"><button className="mobileMenu" aria-label="Toggle navigation" onClick={()=>setNavOpen(!navOpen)}><Menu size={20}/></button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices, customers..."/></div><div className="topActions"><button className="iconBtn"><Bell size={18}/><i/></button><button className="profile" onClick={()=>setMenuOpen(!menuOpen)}><span className="avatar">{user?.email?.slice(0,1).toUpperCase()||'A'}</span><span className="emailText">{user?.email||'Demo workspace'}</span><ChevronDown size={15}/></button>{menuOpen&&<div className="profileMenu"><button onClick={()=>{setPage('Settings');setMenuOpen(false)}}>Settings</button><button onClick={signOut}>Sign out</button></div>}</div></header>
      <section className="content"><div className="pageHead"><div><div className="eyebrow">{page==='Overview'?'YOUR CASHFLOW COMMAND CENTRE':'COLLECTAI'}</div><h1>{page}</h1><p>{page==='Overview'?'See what is owed, what is late, and what needs action today.':page==='Invoices'?'Every invoice. One place. Zero chasing in spreadsheets.':page==='Reminders'?'Keep payment follow-ups consistent without lifting a finger.':page==='Customers'?'Know who owes you and who pays on time.':'Tune your workspace and automation.'}</p></div><div className="actions"><button className="secondary" onClick={()=>setShowImport(true)}><Upload size={17}/> Import CSV</button><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add invoice</button></div></div>
      {page==='Overview'&&<Overview outstanding={outstanding} overdue={overdue} dueSoon={dueSoon} recovered={recovered} invoices={invoices} onAdd={()=>setShowAdd(true)} onImport={()=>setShowImport(true)} setPage={setPage}/>} 
      {page==='Invoices'&&<Invoices filtered={filtered} onAdd={()=>setShowAdd(true)}/>} 
      {page==='Reminders'&&<Reminders invoices={invoices}/>} 
      {page==='Customers'&&<Customers invoices={invoices} customers={customers}/>} 
      {page==='Settings'&&<SettingsPage connected={!!supabase}/>} </section>
    </main>
    {showAdd&&<AddInvoice onClose={()=>setShowAdd(false)} onSave={createInvoice}/>} {showImport&&<ImportModal onClose={()=>setShowImport(false)} onImport={importCsv}/>} {toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}</div>
}
function Nav({icon,label,active,onClick,badge}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void;badge?:number}){return <button className={`nav ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span>{badge? <b>{badge}</b>:null}</button>}
function Stat({title,value,detail,icon}:{title:string;value:string;detail:string;icon:React.ReactNode}){return <div className="stat"><div className="statTop"><span>{title}</span><div className="statIcon">{icon}</div></div><div className="statValue">{value}</div><div className="statDetail">{detail}</div></div>}
function Overview({outstanding,overdue,dueSoon,recovered,invoices,onAdd,onImport,setPage}:{outstanding:number;overdue:number;dueSoon:number;recovered:number;invoices:Invoice[];onAdd:()=>void;onImport:()=>void;setPage:(x:string)=>void}){const recent=invoices.slice(0,5);return <><div className="stats"><Stat title="Outstanding" value={money(outstanding)} detail="Total unpaid balance" icon={<CircleDollarSign size={18}/>}/><Stat title="Overdue" value={money(overdue)} detail={`${invoices.filter(i=>i.status==='overdue').length} invoices need attention`} icon={<Bell size={18}/>}/><Stat title="Due soon" value={money(dueSoon)} detail="Due in the next 7 days" icon={<ArrowUpRight size={18}/>}/><Stat title="Recovered" value={money(recovered)} detail="Payments recorded" icon={<Sparkles size={18}/>}/></div><div className="grid2"><div className="card"><div className="cardHead"><div><h2>Needs attention</h2><p>Invoices where a follow-up can unlock cash.</p></div><button className="textBtn" onClick={()=>setPage('Invoices')}>View all <ArrowUpRight size={15}/></button></div>{recent.filter(i=>i.status!=='paid').length?<div className="invoiceList">{recent.filter(i=>i.status!=='paid').slice(0,4).map(i=><InvoiceRow key={i.id} invoice={i}/>)}</div>:<Empty title="You're all caught up" text="No outstanding invoices need attention."/>}</div><div className="card automation"><div className="pulse"><span></span>LIVE</div><h2>CollectAI is watching.</h2><p>Our automation checks due dates every day and queues appropriate reminders so nothing slips through.</p><div className="rule"></div><div className="automationRow"><div><strong>Daily scan</strong><span>Every day at 9:00 AM</span></div><span className="green">Active</span></div><div className="automationRow"><div><strong>Overdue protection</strong><span>No more than 1 reminder every 7 days</span></div><span className="green">Active</span></div><button className="secondary full" onClick={()=>setPage('Reminders')}>Open reminder centre</button></div></div><div className="quick"><button onClick={onAdd}><Plus size={17}/><div><strong>Add invoice</strong><span>Track a new receivable</span></div></button><button onClick={onImport}><Upload size={17}/><div><strong>Import invoices</strong><span>Upload your CSV in seconds</span></div></button></div></>}
function InvoiceRow({invoice}:{invoice:Invoice}){return <div className="invoiceRow"><div className="invoiceMain"><div className="invoiceAvatar">{invoice.customer_name.slice(0,1).toUpperCase()}</div><div><strong>{invoice.customer_name}</strong><span>{invoice.invoice_number}</span></div></div><div className="amount"><strong>{money(invoice.amount-invoice.amount_paid)}</strong><span>{invoice.status==='overdue'?`${daysLate(invoice.due_date)} days overdue`:`Due ${new Date(invoice.due_date).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}`}</span></div><Status status={invoice.status}/></div>}
function Status({status}:{status:Invoice['status']}){return <span className={`status ${status}`}>{status[0].toUpperCase()+status.slice(1)}</span>}
function Invoices({filtered,onAdd}:{filtered:Invoice[];onAdd:()=>void}){return <div className="card tableCard"><div className="cardHead"><div><h2>Invoices</h2><p>{filtered.length} invoices in workspace</p></div><button className="primary" onClick={onAdd}><Plus size={17}/> Add invoice</button></div><div className="table"><div className="tr th"><span>Invoice</span><span>Customer</span><span>Due</span><span>Amount</span><span>Status</span></div>{filtered.map(i=><div className="tr" key={i.id}><span><strong>{i.invoice_number}</strong></span><span>{i.customer_name}</span><span className={i.status==='overdue'?'late':''}>{new Date(i.due_date).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</span><span>{money(i.amount-i.amount_paid)}</span><span><Status status={i.status}/></span></div>)}</div></div>}
function Reminders({invoices}:{invoices:Invoice[]}){const rows=invoices.filter(i=>i.status==='overdue');return <div className="grid2"><div className="card tableCard"><div className="cardHead"><div><h2>Reminder queue</h2><p>Prepared automatically from overdue invoices.</p></div><span className="queueBadge"><Sparkles size={14}/> Automated</span></div>{rows.length?rows.map(i=><div className="reminderRow" key={i.id}><div><strong>{i.customer_name}</strong><span>{i.invoice_number} · {daysLate(i.due_date)} days overdue</span></div><div><span className="channel">Email</span><span className="scheduled">Queued</span></div></div>):<Empty title="No reminders queued" text="When an invoice becomes overdue, it will appear here."/>}</div><div className="card"><h2>Sequence</h2><p className="muted">A simple, professional follow-up cadence.</p><div className="steps"><Step n="1" title="Friendly nudge" text="1 day overdue"/><Step n="2" title="Payment follow-up" text="7 days overdue"/><Step n="3" title="Escalation" text="14 days overdue"/></div></div></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className="step"><div>{n}</div><span><strong>{title}</strong><em>{text}</em></span></div>}
function Customers({invoices,customers}:{invoices:Invoice[];customers:Customer[]}){const list=customers.length?customers:Array.from(new Map(invoices.map(i=>[i.customer_name,{id:i.customer_name,name:i.customer_name,email:null}])).values());return <div className="card tableCard"><div className="cardHead"><div><h2>Customers</h2><p>{list.length} customer accounts</p></div></div><div className="table"><div className="tr th"><span>Name</span><span>Email</span><span>Outstanding</span><span>Risk</span></div>{list.map(c=>{const ci=invoices.filter(i=>i.customer_name===c.name);const out=ci.reduce((s,i)=>s+(i.amount-i.amount_paid),0);const late=ci.some(i=>i.status==='overdue');return <div className="tr" key={c.id}><span><strong>{c.name}</strong></span><span>{c.email||'—'}</span><span>{money(out)}</span><span><span className={`risk ${late?'high':'low'}`}>{late?'Needs follow-up':'Healthy'}</span></span></div>})}</div></div>}
function SettingsPage({connected}:{connected:boolean}){return <div className="card settingsCard"><div className="settingSection"><h2>Workspace</h2><p>Connect the app to your Lead Supabase project to persist invoices and customers.</p><div className="connection"><span className={`dot ${connected?'on':''}`}></span><div><strong>{connected?'Supabase connected':'Demo mode'}</strong><span>{connected?'Database and authentication are available.':'Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'}</span></div></div></div><div className="settingSection"><h2>Automation</h2><div className="toggleRow"><div><strong>Daily overdue scan</strong><span>Run invoice status refresh and prepare reminders every day.</span></div><div className="toggle on"><i/></div></div></div></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="emptyIcon"><Sparkles size={20}/></div><strong>{title}</strong><span>{text}</span></div>}
function Auth({email,setEmail,password,setPassword,authMode,setAuthMode,auth,loading}:{email:string;setEmail:(v:string)=>void;password:string;setPassword:(v:string)=>void;authMode:'login'|'signup';setAuthMode:(v:'login'|'signup')=>void;auth:()=>void;loading:boolean}){return <div className="auth"><div className="authCard"><div className="brand center"><div className="brandMark"><Zap size={18} fill="currentColor"/></div><span>CollectAI</span></div><div className="authCopy"><h1>{authMode==='login'?'Welcome back.':'Start getting paid faster.'}</h1><p>{authMode==='login'?'Your receivables, under control.':'Automate follow-ups without chasing customers all day.'}</p></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="primary full" onClick={auth} disabled={loading}>{loading?'Working...':authMode==='login'?'Sign in':'Create account'}</button><button className="switch" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?"Don't have an account? Create one":"Already have an account? Sign in"}</button></div></div>}
function AddInvoice({onClose,onSave}:{onClose:()=>void;onSave:(x:any)=>void}){const [form,setForm]=useState({invoice_number:'',customer_name:'',amount:'',amount_paid:'0',due_date:new Date().toISOString().slice(0,10)}); const ok=form.invoice_number&&form.customer_name&&Number(form.amount)>0; return <Modal title="Add invoice" onClose={onClose}><div className="formGrid"><label>Invoice number<input value={form.invoice_number} onChange={e=>setForm({...form,invoice_number:e.target.value})} placeholder="INV-1050"/></label><label>Customer<input value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})} placeholder="Customer name"/></label><label>Amount<input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="50000"/></label><label>Paid<input type="number" value={form.amount_paid} onChange={e=>setForm({...form,amount_paid:e.target.value})} placeholder="0"/></label><label>Due date<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label></div><div className="modalActions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!ok} onClick={()=>onSave({...form,amount:Number(form.amount),amount_paid:Number(form.amount_paid)})}>Save invoice</button></div></Modal>}
function ImportModal({onClose,onImport}:{onClose:()=>void;onImport:(f:File)=>void}){const ref=useRef<HTMLInputElement>(null);return <Modal title="Import invoices" onClose={onClose}><div className="drop" onClick={()=>ref.current?.click()}><Upload size={24}/><strong>Choose a CSV file</strong><span>Columns supported: invoice_number, customer_name, amount, amount_paid, due_date</span><input ref={ref} hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&onImport(e.target.files[0])}/></div><div className="modalActions"><button className="secondary" onClick={onClose}>Cancel</button><button className="textBtn" onClick={()=>ref.current?.click()}>Choose file</button></div></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
